// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import ()

type AirDatum struct {
	ID        int32   `json:"id"`
	Long      float64 `json:"long"`
	Lati      float64 `json:"lati"`
	Timestamp int32   `json:"timestamp"`
	Detail    string  `json:"detail"`
}

type LoginDetail struct {
	RoleID   int32  `json:"role_id"`
	UserID   int32  `json:"user_id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Role struct {
	RoleID   int32  `json:"role_id"`
	RoleName string `json:"role_name"`
}

type User struct {
	UserID    int32  `json:"user_id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}
