// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"time"
)

type AqiDatum struct {
	ID          int32     `json:"id"`
	StationID   string    `json:"station_id"`
	StationName string    `json:"station_name"`
	Aqi         float64   `json:"aqi"`
	MeasureTime string    `json:"measure_time"`
	Epa         string    `json:"epa"`
	Pm25        float64   `json:"pm25"`
	Pm10        float64   `json:"pm10"`
	Ozone       float64   `json:"ozone"`
	No2         float64   `json:"no2"`
	So2         float64   `json:"so2"`
	Co          float64   `json:"co"`
	InsertTime  time.Time `json:"insert_time"`
	UpdatedTime time.Time `json:"updated_time"`
	Latitude    float64   `json:"latitude"`
	Longitude   float64   `json:"longitude"`
}

type BikeDatum struct {
	ID              int32     `json:"id"`
	ContractName    string    `json:"contract_name"`
	Name            string    `json:"name"`
	Address         string    `json:"address"`
	Latitude        float64   `json:"latitude"`
	Longitude       float64   `json:"longitude"`
	Status          string    `json:"status"`
	LastUpdate      time.Time `json:"last_update"`
	Bikes           int32     `json:"bikes"`
	Stands          int32     `json:"stands"`
	MechanicalBikes int32     `json:"mechanical_bikes"`
	ElectricalBikes int32     `json:"electrical_bikes"`
}

type BinDatum struct {
	ID        string  `json:"id"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	Region    int32   `json:"region"`
}

type BusDatum struct {
	VehicleID   string  `json:"vehicle_id"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
	RouteID     string  `json:"route_id"`
	DirectionID int32   `json:"direction_id"`
}

type LoginDetail struct {
	RoleID   int32  `json:"role_id"`
	UserID   int32  `json:"user_id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NoiseDatum struct {
	MonitorID     int32   `json:"monitor_id"`
	Location      string  `json:"location"`
	Latitude      string  `json:"latitude"`
	Longitude     string  `json:"longitude"`
	RecordTime    string  `json:"record_time"`
	Laeq          float64 `json:"laeq"`
	CurrentRating int32   `json:"current_rating"`
	DailyAvg      float64 `json:"daily_avg"`
	HourlyAvg     float64 `json:"hourly_avg"`
}

type PedestrianDatum struct {
	ID           int32     `json:"id"`
	LocationName string    `json:"location_name"`
	Total        int32     `json:"total"`
	Longitude    float64   `json:"longitude"`
	Latitude     float64   `json:"latitude"`
	CounterTime  time.Time `json:"counter_time"`
	InsertTime   time.Time `json:"insert_time"`
	UpdateTime   time.Time `json:"update_time"`
}

type Role struct {
	RoleID   int32  `json:"role_id"`
	RoleName string `json:"role_name"`
	Auths    string `json:"auths"`
}

type User struct {
	UserID    int32  `json:"user_id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}
