// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: pedestrian_data.sql

package db

import (
	"context"
	"time"
)

const createPedestrian = `-- name: CreatePedestrian :one
INSERT INTO pedestrian_data (id,
                             street_name,
                             latitude,
                             longitude,
                             time,
                             amount)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, street_name, latitude, longitude, time, amount
`

type CreatePedestrianParams struct {
	ID         int32     `json:"id"`
	StreetName string    `json:"street_name"`
	Latitude   float64   `json:"latitude"`
	Longitude  float64   `json:"longitude"`
	Time       time.Time `json:"time"`
	Amount     int32     `json:"amount"`
}

func (q *Queries) CreatePedestrian(ctx context.Context, arg CreatePedestrianParams) (PedestrianDatum, error) {
	row := q.db.QueryRowContext(ctx, createPedestrian,
		arg.ID,
		arg.StreetName,
		arg.Latitude,
		arg.Longitude,
		arg.Time,
		arg.Amount,
	)
	var i PedestrianDatum
	err := row.Scan(
		&i.ID,
		&i.StreetName,
		&i.Latitude,
		&i.Longitude,
		&i.Time,
		&i.Amount,
	)
	return i, err
}

const deletePedestrian = `-- name: DeletePedestrian :exec
DELETE
FROM pedestrian_data
WHERE id = $1
`

func (q *Queries) DeletePedestrian(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePedestrian, id)
	return err
}

const getPedestrianByCurrentTime = `-- name: GetPedestrianByCurrentTime :many
SELECT id, street_name, latitude, longitude, time, amount
FROM pedestrian_data
WHERE time = $1
`

func (q *Queries) GetPedestrianByCurrentTime(ctx context.Context, time time.Time) ([]PedestrianDatum, error) {
	rows, err := q.db.QueryContext(ctx, getPedestrianByCurrentTime, time)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PedestrianDatum
	for rows.Next() {
		var i PedestrianDatum
		if err := rows.Scan(
			&i.ID,
			&i.StreetName,
			&i.Latitude,
			&i.Longitude,
			&i.Time,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
