apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
     name: letsencrypt-prod
     namespace: cert-manager
spec:
     acme:
          # Email address used for ACME registration
          email: shritesh.sj99@gmail.com
          # The ACME server URL
          server: https://acme-v02.api.letsencrypt.org/directory
          # Name of a secret used to store the ACME account private key
          privateKeySecretRef:
               name: scm-tls
          # Enable the HTTP-01 challenge provider
          http01:
               ingress:
                    class: nginx
