// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/helloworld1.proto

package helloworld1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Helloworld1 service

func NewHelloworld1Endpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Helloworld1 service

type Helloworld1Service interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Helloworld1_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Helloworld1_PingPongService, error)
}

type helloworld1Service struct {
	c    client.Client
	name string
}

func NewHelloworld1Service(name string, c client.Client) Helloworld1Service {
	return &helloworld1Service{
		c:    c,
		name: name,
	}
}

func (c *helloworld1Service) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Helloworld1.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloworld1Service) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Helloworld1_StreamService, error) {
	req := c.c.NewRequest(c.name, "Helloworld1.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &helloworld1ServiceStream{stream}, nil
}

type Helloworld1_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type helloworld1ServiceStream struct {
	stream client.Stream
}

func (x *helloworld1ServiceStream) Close() error {
	return x.stream.Close()
}

func (x *helloworld1ServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *helloworld1ServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloworld1ServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloworld1ServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloworld1Service) PingPong(ctx context.Context, opts ...client.CallOption) (Helloworld1_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Helloworld1.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &helloworld1ServicePingPong{stream}, nil
}

type Helloworld1_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type helloworld1ServicePingPong struct {
	stream client.Stream
}

func (x *helloworld1ServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *helloworld1ServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *helloworld1ServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloworld1ServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloworld1ServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *helloworld1ServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Helloworld1 service

type Helloworld1Handler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Helloworld1_StreamStream) error
	PingPong(context.Context, Helloworld1_PingPongStream) error
}

func RegisterHelloworld1Handler(s server.Server, hdlr Helloworld1Handler, opts ...server.HandlerOption) error {
	type helloworld1 interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Helloworld1 struct {
		helloworld1
	}
	h := &helloworld1Handler{hdlr}
	return s.Handle(s.NewHandler(&Helloworld1{h}, opts...))
}

type helloworld1Handler struct {
	Helloworld1Handler
}

func (h *helloworld1Handler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.Helloworld1Handler.Call(ctx, in, out)
}

func (h *helloworld1Handler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.Helloworld1Handler.Stream(ctx, m, &helloworld1StreamStream{stream})
}

type Helloworld1_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type helloworld1StreamStream struct {
	stream server.Stream
}

func (x *helloworld1StreamStream) Close() error {
	return x.stream.Close()
}

func (x *helloworld1StreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *helloworld1StreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloworld1StreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloworld1StreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *helloworld1Handler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.Helloworld1Handler.PingPong(ctx, &helloworld1PingPongStream{stream})
}

type Helloworld1_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type helloworld1PingPongStream struct {
	stream server.Stream
}

func (x *helloworld1PingPongStream) Close() error {
	return x.stream.Close()
}

func (x *helloworld1PingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *helloworld1PingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *helloworld1PingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *helloworld1PingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *helloworld1PingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
