serviceName: gateway
serviceType: gateway
serviceUrl: gateway-service
Honeybadger_API_KEY: hbp_bJUOVJUnJVjpirxdj6T9EZ3s4Pxech1eVRpL
development: true
http:
     port: 8000
     development: true
     basePath: /
     debugErrorsResponse: true
probes:
     readinessPath: /live
     livenessPath: /ready
     port: :8002
     pprof: :6001
     prometheusPath: /metrics
     prometheusPort: :8001
     checkIntervalSeconds: 10
logger:
     level: info
     devMode: false
     encoder: json
db:
     DB_SOURCE: postgresql://group_admin:group007@18.202.24.40:5432/masterdb?sslmode=disable
     DB_DRIVER: postgres
     AIR_TOKEN: d3f5d975618dc64e01ed3df11688671d3e61dd7f
ConnectedServices:
     - serviceName: AirService
       serviceType: service
       serviceUrl: air-service
       healthcheckPort: 4002
       grpcPort: 4000
     - serviceName: BusService
       serviceType: service
       serviceUrl: bus-service
       healthcheckPort: 6002
       grpcPort: 6000
     - serviceName: BikeService
       serviceType: service
       serviceUrl: bike-service
       healthcheckPort: 5002
       grpcPort: 5000
     - serviceName: BinService
       serviceType: service
       serviceUrl: bin-service
       healthcheckPort: 7002
       grpcPort: 7000
