serviceName: search_service
http:
     port: :8000
     development: true
     basePath: /api/v1
     debugErrorsResponse: true
     ignoreLogUrls: ["metrics", "swagger"]
probes:
     readinessPath: /ready
     livenessPath: /live
     port: :3001
     pprof: :6001
     prometheusPath: /metrics
     prometheusPort: :8001
     checkIntervalSeconds: 10
logger:
     level: debug
     devMode: false
     encoder: console
timeouts:
     postgresInitMilliseconds: 1500
     postgresInitRetryCount: 3
