serviceName: gateway
serviceType: gateway
serviceUrl: http://localhost
Honeybadger_API_KEY: hbp_bJUOVJUnJVjpirxdj6T9EZ3s4Pxech1eVRpL
http:
     port: 8000
     development: true
     basePath: /
     debugErrorsResponse: true
probes:
     readinessPath: /live
     livenessPath: /ready
     port: 8002
     prometheusPath: /metrics
     prometheusPort: 8001
     checkIntervalSeconds: 10
logger:
     level: info
     devMode: false
     encoder: json
db:
     DB_SOURCE: postgresql://group_admin:group007@sustainable-city-management.cdxqy8kbzxjs.eu-west-1.rds.amazonaws.com:5432/masterdb?sslmode=disable
     DB_DRIVER: postgres
     AIR_TOKEN: d3f5d975618dc64e01ed3df11688671d3e61dd7f
ConnectedServices:
     - serviceName: air
       serviceType: service
       serviceUrl: http://localhost
       healthcheckPort: 4002
       grpcPort: 4000
     - serviceName: bike
       serviceType: service
       serviceUrl: http://localhost
       healthcheckPort: 5002
       grpcPort: 5000
     - serviceName: bin
       serviceType: service
       serviceUrl: http://localhost
       healthcheckPort: 7002
       grpcPort: 7002
     - serviceName: bus
       serviceType: service
       serviceUrl: http://localhost
       healthcheckPort: 6002
       grpcPort: 6000
