version: "3.9"

services:
     microservice:
          build:
               context: .
               dockerfile: Dockerfile
          container_name: main
          restart: always
          ports:
               - "8080:8080"
               - "3000:3000"
          environment:
               - RABBITMQ_URI=amqp://guest:guest@host.docker.internal:5672/
          depends_on:
               - grafana
               - rabbitmq
               - node_exporter
          networks: ["sustinable-city-management"]

     rabbitmq:
          image: rabbitmq:3.9-management-alpine
          container_name: rabbitmq
          restart: always
          ports:
               - "5672:5672"
               - "15672:15672"
          networks: ["sustinable-city-management"]

     jaeger:
          container_name: jaeger_container
          restart: always
          image: jaegertracing/all-in-one:1.35
          environment:
               - COLLECTOR_ZIPKIN_HTTP_PORT=9411
          ports:
               - "5775:5775/udp"
               - "6831:6831/udp"
               - "6832:6832/udp"
               - "5778:5778"
               - "16686:16686"
               - "14268:14268"
               - "14250:14250"
               - "9411:9411"
          networks: ["sustinable-city-management"]

     prometheus:
          image: prom/prometheus:latest
          container_name: prometheus
          ports:
               - "9090:9090"
          volumes:
               - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
          command:
               - --config.file=/etc/prometheus/prometheus.yaml
          networks: ["sustinable-city-management"]

     node_exporter:
          container_name: node_exporter_container
          restart: always
          image: prom/node-exporter
          ports:
               - "9101:9100"
          networks: ["sustinable-city-management"]

     grafana:
          container_name: grafana_container
          restart: always
          image: grafana/grafana
          ports:
               - "3005:3000"
          networks: ["sustinable-city-management"]

networks:
     sustinable-city-management:
          name: sustinable-city-management
