// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: bus_service/bus_service.proto

package bus_pd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusNilRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BusNilRequest) Reset() {
	*x = BusNilRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bus_service_bus_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusNilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusNilRequest) ProtoMessage() {}

func (x *BusNilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bus_service_bus_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusNilRequest.ProtoReflect.Descriptor instead.
func (*BusNilRequest) Descriptor() ([]byte, []int) {
	return file_bus_service_bus_service_proto_rawDescGZIP(), []int{0}
}

type RouteIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RouteIdRequest) Reset() {
	*x = RouteIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bus_service_bus_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteIdRequest) ProtoMessage() {}

func (x *RouteIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bus_service_bus_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteIdRequest.ProtoReflect.Descriptor instead.
func (*RouteIdRequest) Descriptor() ([]byte, []int) {
	return file_bus_service_bus_service_proto_rawDescGZIP(), []int{1}
}

func (x *RouteIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BusJsonStringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BusJsonStringResponse) Reset() {
	*x = BusJsonStringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bus_service_bus_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusJsonStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusJsonStringResponse) ProtoMessage() {}

func (x *BusJsonStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bus_service_bus_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusJsonStringResponse.ProtoReflect.Descriptor instead.
func (*BusJsonStringResponse) Descriptor() ([]byte, []int) {
	return file_bus_service_bus_service_proto_rawDescGZIP(), []int{2}
}

func (x *BusJsonStringResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_bus_service_bus_service_proto protoreflect.FileDescriptor

var file_bus_service_bus_service_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x62, 0x75, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62, 0x75,
	0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x0f, 0x0a, 0x0d, 0x42, 0x75, 0x73, 0x4e, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x20, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x42, 0x75, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x4e, 0x0a, 0x0a, 0x42, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x44, 0x61, 0x74,
	0x61, 0x42, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x12, 0x0f, 0x2e, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x42, 0x75,
	0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x62, 0x75, 0x73, 0x2f, 0x62, 0x75, 0x73,
	0x2d, 0x70, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bus_service_bus_service_proto_rawDescOnce sync.Once
	file_bus_service_bus_service_proto_rawDescData = file_bus_service_bus_service_proto_rawDesc
)

func file_bus_service_bus_service_proto_rawDescGZIP() []byte {
	file_bus_service_bus_service_proto_rawDescOnce.Do(func() {
		file_bus_service_bus_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_bus_service_bus_service_proto_rawDescData)
	})
	return file_bus_service_bus_service_proto_rawDescData
}

var file_bus_service_bus_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bus_service_bus_service_proto_goTypes = []interface{}{
	(*BusNilRequest)(nil),         // 0: BusNilRequest
	(*RouteIdRequest)(nil),        // 1: RouteIdRequest
	(*BusJsonStringResponse)(nil), // 2: BusJsonStringResponse
}
var file_bus_service_bus_service_proto_depIdxs = []int32{
	1, // 0: BusService.GetBusDataByRouteId:input_type -> RouteIdRequest
	2, // 1: BusService.GetBusDataByRouteId:output_type -> BusJsonStringResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bus_service_bus_service_proto_init() }
func file_bus_service_bus_service_proto_init() {
	if File_bus_service_bus_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bus_service_bus_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusNilRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bus_service_bus_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bus_service_bus_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusJsonStringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bus_service_bus_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bus_service_bus_service_proto_goTypes,
		DependencyIndexes: file_bus_service_bus_service_proto_depIdxs,
		MessageInfos:      file_bus_service_bus_service_proto_msgTypes,
	}.Build()
	File_bus_service_bus_service_proto = out.File
	file_bus_service_bus_service_proto_rawDesc = nil
	file_bus_service_bus_service_proto_goTypes = nil
	file_bus_service_bus_service_proto_depIdxs = nil
}
