// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: bus_service/bus_service.proto

package bus_pd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusNilRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BusNilRequest) Reset() {
	*x = BusNilRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bus_service_bus_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusNilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusNilRequest) ProtoMessage() {}

func (x *BusNilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bus_service_bus_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusNilRequest.ProtoReflect.Descriptor instead.
func (*BusNilRequest) Descriptor() ([]byte, []int) {
	return file_bus_service_bus_service_proto_rawDescGZIP(), []int{0}
}

type RouteIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RouteIdRequest) Reset() {
	*x = RouteIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bus_service_bus_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteIdRequest) ProtoMessage() {}

func (x *RouteIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bus_service_bus_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteIdRequest.ProtoReflect.Descriptor instead.
func (*RouteIdRequest) Descriptor() ([]byte, []int) {
	return file_bus_service_bus_service_proto_rawDescGZIP(), []int{1}
}

func (x *RouteIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBusDataByRouteIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusData []*InsideGetBusDataByRouteIdResponse `protobuf:"bytes,1,rep,name=busData,proto3" json:"busData,omitempty"`
}

func (x *GetBusDataByRouteIdResponse) Reset() {
	*x = GetBusDataByRouteIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bus_service_bus_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBusDataByRouteIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusDataByRouteIdResponse) ProtoMessage() {}

func (x *GetBusDataByRouteIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bus_service_bus_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusDataByRouteIdResponse.ProtoReflect.Descriptor instead.
func (*GetBusDataByRouteIdResponse) Descriptor() ([]byte, []int) {
	return file_bus_service_bus_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetBusDataByRouteIdResponse) GetBusData() []*InsideGetBusDataByRouteIdResponse {
	if x != nil {
		return x.BusData
	}
	return nil
}

type InsideGetBusDataByRouteIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VehicleID   string  `protobuf:"bytes,1,opt,name=vehicleID,proto3" json:"vehicleID,omitempty"`
	Latitude    float32 `protobuf:"fixed32,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude   float32 `protobuf:"fixed32,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RouteID     string  `protobuf:"bytes,4,opt,name=routeID,proto3" json:"routeID,omitempty"`
	DirectionID int32   `protobuf:"varint,5,opt,name=directionID,proto3" json:"directionID,omitempty"`
}

func (x *InsideGetBusDataByRouteIdResponse) Reset() {
	*x = InsideGetBusDataByRouteIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bus_service_bus_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsideGetBusDataByRouteIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsideGetBusDataByRouteIdResponse) ProtoMessage() {}

func (x *InsideGetBusDataByRouteIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bus_service_bus_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsideGetBusDataByRouteIdResponse.ProtoReflect.Descriptor instead.
func (*InsideGetBusDataByRouteIdResponse) Descriptor() ([]byte, []int) {
	return file_bus_service_bus_service_proto_rawDescGZIP(), []int{3}
}

func (x *InsideGetBusDataByRouteIdResponse) GetVehicleID() string {
	if x != nil {
		return x.VehicleID
	}
	return ""
}

func (x *InsideGetBusDataByRouteIdResponse) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *InsideGetBusDataByRouteIdResponse) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *InsideGetBusDataByRouteIdResponse) GetRouteID() string {
	if x != nil {
		return x.RouteID
	}
	return ""
}

func (x *InsideGetBusDataByRouteIdResponse) GetDirectionID() int32 {
	if x != nil {
		return x.DirectionID
	}
	return 0
}

var File_bus_service_bus_service_proto protoreflect.FileDescriptor

var file_bus_service_bus_service_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x62, 0x75, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62, 0x75,
	0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x0f, 0x0a, 0x0d, 0x42, 0x75, 0x73, 0x4e, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x20, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x5b, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x42, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3c, 0x0a, 0x07, 0x62, 0x75, 0x73, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x49, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x47, 0x65, 0x74, 0x42, 0x75,
	0x73, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x62, 0x75, 0x73, 0x44, 0x61, 0x74, 0x61, 0x22,
	0xb7, 0x01, 0x0a, 0x21, 0x49, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x32, 0x54, 0x0a, 0x0a, 0x42, 0x75, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x75,
	0x73, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x12, 0x0f,
	0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0c, 0x5a, 0x0a, 0x62, 0x75, 0x73, 0x2f, 0x62, 0x75, 0x73, 0x2d, 0x70, 0x64, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bus_service_bus_service_proto_rawDescOnce sync.Once
	file_bus_service_bus_service_proto_rawDescData = file_bus_service_bus_service_proto_rawDesc
)

func file_bus_service_bus_service_proto_rawDescGZIP() []byte {
	file_bus_service_bus_service_proto_rawDescOnce.Do(func() {
		file_bus_service_bus_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_bus_service_bus_service_proto_rawDescData)
	})
	return file_bus_service_bus_service_proto_rawDescData
}

var file_bus_service_bus_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bus_service_bus_service_proto_goTypes = []interface{}{
	(*BusNilRequest)(nil),                     // 0: BusNilRequest
	(*RouteIdRequest)(nil),                    // 1: RouteIdRequest
	(*GetBusDataByRouteIdResponse)(nil),       // 2: GetBusDataByRouteIdResponse
	(*InsideGetBusDataByRouteIdResponse)(nil), // 3: InsideGetBusDataByRouteIdResponse
}
var file_bus_service_bus_service_proto_depIdxs = []int32{
	3, // 0: GetBusDataByRouteIdResponse.busData:type_name -> InsideGetBusDataByRouteIdResponse
	1, // 1: BusService.GetBusDataByRouteId:input_type -> RouteIdRequest
	2, // 2: BusService.GetBusDataByRouteId:output_type -> GetBusDataByRouteIdResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bus_service_bus_service_proto_init() }
func file_bus_service_bus_service_proto_init() {
	if File_bus_service_bus_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bus_service_bus_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusNilRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bus_service_bus_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bus_service_bus_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBusDataByRouteIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bus_service_bus_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsideGetBusDataByRouteIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bus_service_bus_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bus_service_bus_service_proto_goTypes,
		DependencyIndexes: file_bus_service_bus_service_proto_depIdxs,
		MessageInfos:      file_bus_service_bus_service_proto_msgTypes,
	}.Build()
	File_bus_service_bus_service_proto = out.File
	file_bus_service_bus_service_proto_rawDesc = nil
	file_bus_service_bus_service_proto_goTypes = nil
	file_bus_service_bus_service_proto_depIdxs = nil
}
