// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: airquality_service/air.proto

package air_pd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AirIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StationId string `protobuf:"bytes,1,opt,name=stationId,proto3" json:"stationId,omitempty"`
}

func (x *AirIdRequest) Reset() {
	*x = AirIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_airquality_service_air_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirIdRequest) ProtoMessage() {}

func (x *AirIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_airquality_service_air_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirIdRequest.ProtoReflect.Descriptor instead.
func (*AirIdRequest) Descriptor() ([]byte, []int) {
	return file_airquality_service_air_proto_rawDescGZIP(), []int{0}
}

func (x *AirIdRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

type GetAirDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetAirDataResponse) Reset() {
	*x = GetAirDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_airquality_service_air_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAirDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAirDataResponse) ProtoMessage() {}

func (x *GetAirDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_airquality_service_air_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAirDataResponse.ProtoReflect.Descriptor instead.
func (*GetAirDataResponse) Descriptor() ([]byte, []int) {
	return file_airquality_service_air_proto_rawDescGZIP(), []int{1}
}

func (x *GetAirDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAQIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetAQIResponse) Reset() {
	*x = GetAQIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_airquality_service_air_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAQIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAQIResponse) ProtoMessage() {}

func (x *GetAQIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_airquality_service_air_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAQIResponse.ProtoReflect.Descriptor instead.
func (*GetAQIResponse) Descriptor() ([]byte, []int) {
	return file_airquality_service_air_proto_rawDescGZIP(), []int{2}
}

func (x *GetAQIResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_airquality_service_air_proto protoreflect.FileDescriptor

var file_airquality_service_air_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x69, 0x72, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c,
	0x0a, 0x0c, 0x41, 0x69, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x41, 0x69, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x41, 0x51, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x69, 0x0a, 0x03, 0x41, 0x69, 0x72, 0x12,
	0x32, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x69, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0d, 0x2e,
	0x41, 0x69, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x69, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x51, 0x49, 0x12, 0x0d, 0x2e,
	0x41, 0x69, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x69, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x61, 0x69, 0x72, 0x2d, 0x71, 0x75, 0x61, 0x6c, 0x69,
	0x74, 0x79, 0x2f, 0x61, 0x69, 0x72, 0x2d, 0x70, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_airquality_service_air_proto_rawDescOnce sync.Once
	file_airquality_service_air_proto_rawDescData = file_airquality_service_air_proto_rawDesc
)

func file_airquality_service_air_proto_rawDescGZIP() []byte {
	file_airquality_service_air_proto_rawDescOnce.Do(func() {
		file_airquality_service_air_proto_rawDescData = protoimpl.X.CompressGZIP(file_airquality_service_air_proto_rawDescData)
	})
	return file_airquality_service_air_proto_rawDescData
}

var file_airquality_service_air_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_airquality_service_air_proto_goTypes = []interface{}{
	(*AirIdRequest)(nil),       // 0: AirIdRequest
	(*GetAirDataResponse)(nil), // 1: GetAirDataResponse
	(*GetAQIResponse)(nil),     // 2: GetAQIResponse
}
var file_airquality_service_air_proto_depIdxs = []int32{
	0, // 0: Air.GetAirData:input_type -> AirIdRequest
	0, // 1: Air.GetAQI:input_type -> AirIdRequest
	1, // 2: Air.GetAirData:output_type -> GetAirDataResponse
	1, // 3: Air.GetAQI:output_type -> GetAirDataResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_airquality_service_air_proto_init() }
func file_airquality_service_air_proto_init() {
	if File_airquality_service_air_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_airquality_service_air_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_airquality_service_air_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAirDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_airquality_service_air_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAQIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_airquality_service_air_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_airquality_service_air_proto_goTypes,
		DependencyIndexes: file_airquality_service_air_proto_depIdxs,
		MessageInfos:      file_airquality_service_air_proto_msgTypes,
	}.Build()
	File_airquality_service_air_proto = out.File
	file_airquality_service_air_proto_rawDesc = nil
	file_airquality_service_air_proto_goTypes = nil
	file_airquality_service_air_proto_depIdxs = nil
}
