// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: airquality_service/air.proto

package air_pd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AirClient is the client API for Air service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AirClient interface {
	GetAirData(ctx context.Context, in *AirIdRequest, opts ...grpc.CallOption) (*GetAirDataResponse, error)
	GetAQI(ctx context.Context, in *AirIdRequest, opts ...grpc.CallOption) (*GetAirDataResponse, error)
}

type airClient struct {
	cc grpc.ClientConnInterface
}

func NewAirClient(cc grpc.ClientConnInterface) AirClient {
	return &airClient{cc}
}

func (c *airClient) GetAirData(ctx context.Context, in *AirIdRequest, opts ...grpc.CallOption) (*GetAirDataResponse, error) {
	out := new(GetAirDataResponse)
	err := c.cc.Invoke(ctx, "/Air/GetAirData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airClient) GetAQI(ctx context.Context, in *AirIdRequest, opts ...grpc.CallOption) (*GetAirDataResponse, error) {
	out := new(GetAirDataResponse)
	err := c.cc.Invoke(ctx, "/Air/GetAQI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AirServer is the server API for Air service.
// All implementations must embed UnimplementedAirServer
// for forward compatibility
type AirServer interface {
	GetAirData(context.Context, *AirIdRequest) (*GetAirDataResponse, error)
	GetAQI(context.Context, *AirIdRequest) (*GetAirDataResponse, error)
	mustEmbedUnimplementedAirServer()
}

// UnimplementedAirServer must be embedded to have forward compatible implementations.
type UnimplementedAirServer struct {
}

func (UnimplementedAirServer) GetAirData(context.Context, *AirIdRequest) (*GetAirDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAirData not implemented")
}
func (UnimplementedAirServer) GetAQI(context.Context, *AirIdRequest) (*GetAirDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAQI not implemented")
}
func (UnimplementedAirServer) mustEmbedUnimplementedAirServer() {}

// UnsafeAirServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AirServer will
// result in compilation errors.
type UnsafeAirServer interface {
	mustEmbedUnimplementedAirServer()
}

func RegisterAirServer(s grpc.ServiceRegistrar, srv AirServer) {
	s.RegisterService(&Air_ServiceDesc, srv)
}

func _Air_GetAirData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AirIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirServer).GetAirData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Air/GetAirData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirServer).GetAirData(ctx, req.(*AirIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Air_GetAQI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AirIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirServer).GetAQI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Air/GetAQI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirServer).GetAQI(ctx, req.(*AirIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Air_ServiceDesc is the grpc.ServiceDesc for Air service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Air_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Air",
	HandlerType: (*AirServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAirData",
			Handler:    _Air_GetAirData_Handler,
		},
		{
			MethodName: "GetAQI",
			Handler:    _Air_GetAQI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "airquality_service/air.proto",
}
