// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type LoginDetail struct {
	RoleID   sql.NullInt32  `json:"role_id"`
	UserID   sql.NullInt32  `json:"user_id"`
	Email    string         `json:"email"`
	Password sql.NullString `json:"password"`
}

type Role struct {
	RoleID   int32  `json:"role_id"`
	RoleName string `json:"role_name"`
}

type User struct {
	UserID    int32  `json:"user_id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}
