// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: bike_service/bike_service.proto

package bike_pd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBikesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBikesRequest) Reset() {
	*x = GetBikesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_service_bike_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBikesRequest) ProtoMessage() {}

func (x *GetBikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bike_service_bike_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBikesRequest.ProtoReflect.Descriptor instead.
func (*GetBikesRequest) Descriptor() ([]byte, []int) {
	return file_bike_service_bike_service_proto_rawDescGZIP(), []int{0}
}

type GetBikesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bikes []*Bike `protobuf:"bytes,1,rep,name=bikes,proto3" json:"bikes,omitempty"`
}

func (x *GetBikesResponse) Reset() {
	*x = GetBikesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_service_bike_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBikesResponse) ProtoMessage() {}

func (x *GetBikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bike_service_bike_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBikesResponse.ProtoReflect.Descriptor instead.
func (*GetBikesResponse) Descriptor() ([]byte, []int) {
	return file_bike_service_bike_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetBikesResponse) GetBikes() []*Bike {
	if x != nil {
		return x.Bikes
	}
	return nil
}

type Bike struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ContractName    string  `protobuf:"bytes,2,opt,name=contractName,proto3" json:"contractName,omitempty"`
	Name            string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address         string  `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Latitude        float32 `protobuf:"fixed32,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude       float32 `protobuf:"fixed32,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Status          string  `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	LastUpdate      int64   `protobuf:"varint,8,opt,name=lastUpdate,proto3" json:"lastUpdate,omitempty"`
	Bikes           int32   `protobuf:"varint,9,opt,name=bikes,proto3" json:"bikes,omitempty"`
	Stands          int32   `protobuf:"varint,10,opt,name=stands,proto3" json:"stands,omitempty"`
	MechanicalBikes int32   `protobuf:"varint,11,opt,name=mechanicalBikes,proto3" json:"mechanicalBikes,omitempty"`
	ElectricalBikes int32   `protobuf:"varint,12,opt,name=electricalBikes,proto3" json:"electricalBikes,omitempty"`
}

func (x *Bike) Reset() {
	*x = Bike{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_service_bike_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bike) ProtoMessage() {}

func (x *Bike) ProtoReflect() protoreflect.Message {
	mi := &file_bike_service_bike_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bike.ProtoReflect.Descriptor instead.
func (*Bike) Descriptor() ([]byte, []int) {
	return file_bike_service_bike_service_proto_rawDescGZIP(), []int{2}
}

func (x *Bike) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bike) GetContractName() string {
	if x != nil {
		return x.ContractName
	}
	return ""
}

func (x *Bike) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bike) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Bike) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Bike) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Bike) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Bike) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

func (x *Bike) GetBikes() int32 {
	if x != nil {
		return x.Bikes
	}
	return 0
}

func (x *Bike) GetStands() int32 {
	if x != nil {
		return x.Stands
	}
	return 0
}

func (x *Bike) GetMechanicalBikes() int32 {
	if x != nil {
		return x.MechanicalBikes
	}
	return 0
}

func (x *Bike) GetElectricalBikes() int32 {
	if x != nil {
		return x.ElectricalBikes
	}
	return 0
}

var File_bike_service_bike_service_proto protoreflect.FileDescriptor

var file_bike_service_bike_service_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x62, 0x69, 0x6b, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62,
	0x69, 0x6b, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x2f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x62, 0x69, 0x6b, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x05,
	0x62, 0x69, 0x6b, 0x65, 0x73, 0x22, 0xdc, 0x02, 0x0a, 0x04, 0x42, 0x69, 0x6b, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x6e,
	0x64, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x73,
	0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x65, 0x63, 0x68, 0x61, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x42, 0x69,
	0x6b, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x6d, 0x65, 0x63, 0x68, 0x61,
	0x6e, 0x69, 0x63, 0x61, 0x6c, 0x42, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x42, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0f, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x42,
	0x69, 0x6b, 0x65, 0x73, 0x32, 0x40, 0x0a, 0x0b, 0x42, 0x69, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x73, 0x12,
	0x10, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x62, 0x69, 0x6b, 0x65, 0x2f, 0x62,
	0x69, 0x6b, 0x65, 0x2d, 0x70, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bike_service_bike_service_proto_rawDescOnce sync.Once
	file_bike_service_bike_service_proto_rawDescData = file_bike_service_bike_service_proto_rawDesc
)

func file_bike_service_bike_service_proto_rawDescGZIP() []byte {
	file_bike_service_bike_service_proto_rawDescOnce.Do(func() {
		file_bike_service_bike_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_bike_service_bike_service_proto_rawDescData)
	})
	return file_bike_service_bike_service_proto_rawDescData
}

var file_bike_service_bike_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bike_service_bike_service_proto_goTypes = []interface{}{
	(*GetBikesRequest)(nil),  // 0: GetBikesRequest
	(*GetBikesResponse)(nil), // 1: GetBikesResponse
	(*Bike)(nil),             // 2: Bike
}
var file_bike_service_bike_service_proto_depIdxs = []int32{
	2, // 0: GetBikesResponse.bikes:type_name -> Bike
	0, // 1: BikeService.GetBikes:input_type -> GetBikesRequest
	1, // 2: BikeService.GetBikes:output_type -> GetBikesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bike_service_bike_service_proto_init() }
func file_bike_service_bike_service_proto_init() {
	if File_bike_service_bike_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bike_service_bike_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBikesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_service_bike_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBikesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_service_bike_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bike); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bike_service_bike_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bike_service_bike_service_proto_goTypes,
		DependencyIndexes: file_bike_service_bike_service_proto_depIdxs,
		MessageInfos:      file_bike_service_bike_service_proto_msgTypes,
	}.Build()
	File_bike_service_bike_service_proto = out.File
	file_bike_service_bike_service_proto_rawDesc = nil
	file_bike_service_bike_service_proto_goTypes = nil
	file_bike_service_bike_service_proto_depIdxs = nil
}
