name: Backend-CI

on:
     push:
          branches:
               - backend
          paths:
               - "backend/*"
     pull_request:
          branches:
               - backend
          paths:
               - "backend/*"
     workflow_dispatch:

jobs:
     build:
          runs-on: ubuntu-latest
          environment: backend
          steps:
               - name: Checkout backend
                 uses: actions/checkout@v2
                 with:
                      ref: backend

               - name: Log in to Docker Hub
                 uses: docker/login-action@v2
                 with:
                      username: ${{ secrets.DOCKER_USERNAME }}
                      password: ${{ secrets.DOCKER_PASSWORD }}

               - name: Run Docker build
                 run: |
                      cd backend
                      make docker-build

               - name: Run Docker Upload
                 run: |
                      cd backend
                      make docker-upload

               - name: Install doctl
                 uses: digitalocean/action-doctl@v2
                 with:
                      token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

               - name: Save DigitalOcean kubeconfig with short-lived credentials
                 run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 scm-cluster

               - name: Stop App
                 run: |
                      cd backend
                      make uninstall_app

               - name: Run App
                 run: |
                      cd backend
                      make install_app
